---
- name: Add the group minio
  group:
    name: '{{ minio_arg.user }}'
    gid: '{{ minio_arg.uid }}'

- name: Add the user minio
  user:
    name: '{{ minio_arg.user }}'
    comment: '{{ minio_arg.user }}'
    create_home: 'no'
    shell: '/sbin/nologin'
    uid: '{{ minio_arg.uid }}'
    group: '{{ minio_arg.user }}'

- name: Creating Minio tenants drives
  file:
    dest: '{{ minio_path }}/minio/T{{ item|int }}'
    state: directory
    owner: '{{ minio_arg.user }}'
    group: '{{ minio_arg.user }}'
    mode: 0755
  with_sequence: start=1 end={{ minio_tenants|int }}

- name: Configure kernel parameters
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: 'yes'
    sysctl_set: 'yes'
    sysctl_file: '/etc/sysctl.d/20-sysctl.conf'
  with_items:
    - '{{ minio_kernel_parameters }}'

- name: Minio configure file transfer
  template:
    src: 'minio.default.j2'
    dest: '/etc/default/minio-T{{ item|int }}'
    owner: 'root'
    group: 'root'
    mode: 0644
  with_sequence: start=1 end={{ minio_tenants|int }}
  no_log: true
  register: soft_config

- name: Minio systemd service file transfer
  template:
    src: 'minio.service.j2'
    dest: '/lib/systemd/system/minio-T{{ item|int }}.service'
    owner: 'root'
    group: 'root'
    mode: 0644
  with_sequence: start=1 end={{ minio_tenants|int }}
  register: soft_systemd
