---
- name: Check current minio version
  command: '/usr/local/bin/minio --version'
  register: minio_current_version
  changed_when: false
  failed_when: false

- name: Install minio server & client
  get_url:
    url: '{{ minio_soft_url }}/{{ item.state }}/{{ item.file }}/release/{{ ansible_system|lower }}-{{ architecture[ansible_architecture] }}/{{ item.file}}'
    dest: '/usr/local/bin/{{ item.file }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    timeout: '60'
    force: 'yes'
    validate_certs: 'no'
  loop:
    - { state: 'client', file: 'mc' }
    - { state: 'server', file: 'minio' }
  when: minio_current_version.rc == 2
  register: soft_update
  ignore_errors: true
