---
- name: Erasure endpoints check.
  debug:
    msg: 'Invalid total number of endpoints for erasure mode, Please provide an even number of endpoints greater or equal to 4, For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide.'
  when:
    - minio_servers | length > 1
    - minio_servers | length * minio_drives < 4

- name: Minio operation.
  block:
    - name: Proxy traffic using NGinx.
      include: 'nginx.yml'
      when: minio_ngx_dept | bool
    - name: Include tasks for specific OS.
      include: '{{ ansible_os_family }}.yml'
    - name: Straight to getenforce selinux status.
      include: 'selinux.yml'
    - name: Configure the minio firewall.
      include: 'firewall.yml'
    - name: Installation the minio.
      include: 'install.yml'
    - name: Configuration the minio.
      include: 'configureation.yml'
    - name: Include certificate tasks.
      include: 'certificates.yml'
    - name: Force the handler to run immediately.
      meta: flush_handlers
    - name: Include prometheus exporter tasks.
      include: 'register.yml'
      loop: '{{ consul_public_clients }}'
      loop_control:
        loop_var: consul_public_clients_item
      when: consul_public_register | bool
    - name: Bucket operation.
      include: 'bucket.yml'
      when:
        - minio_servers[0] in ansible_default_ipv4.address
        - minio_tenants is defined
  when: minio_servers == 1 or minio_servers | length * minio_drives > 3