---
- name: Erasure endpoints check
  debug:
    msg: 'Invalid total number of endpoints for erasure mode, Please provide an even number of endpoints greater or equal to 4, For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide.'
  when:
    - minio_servers | length > 1
    - minio_servers | length < 4

- name: Minio operation
  block:
    - name: Configure the minio firewall
      include: 'firewall.yml'
    - name: Installation the minio
      include: 'install.yml'
    - name: Configuration the minio
      include: 'configureation.yml'
    - name: Reload the minio service
      shell: echo ''
      notify: 'Ensure minio service is enabled'
      when: soft_update is changed or soft_config is changed or soft_systemd is changed
    - name: Force the handler to run immediately
      meta: flush_handlers
    - include_tasks: 'register.yml'
      with_items:
        - '{{ consul_public_clients }}'
      loop_control:
         loop_var: consul_public_clients_item
      when: consul_public_register | bool
  when: minio_servers | length == 1 or minio_servers | length > 3
