---
- name: Create tenants site variables arrays.
  set_fact:
    minio_ngx_site: []

- name: Gather tenants site variables for NGinx.
  set_fact:
    minio_ngx_site: '{{ minio_ngx_site + [ { "domain": item + "." + datacenter + "." + domain ,"syntax":["location / {","  proxy_buffering off;","  proxy_set_header Host $http_host;","  proxy_http_version 1.1;","  proxy_read_timeout 15m;","  proxy_send_timeout 15m;","  proxy_request_buffering off;","  client_max_body_size "+minio_ngx_client_max_body_size+";","  valid_referers none "+item+";","  if ($invalid_referer) { return 403; }","  proxy_pass https://backend_" + item + "." + datacenter + "." + domain + "/;","}"],"backend_address": minio_servers,"backend_port": minio_api_start_port | int + 1 + index,"sticky": "ip_hash","keepaliv": ansible_processor_vcpus * 4 } ] }}'
  loop: '{{ minio_tenants }}'
  loop_control:
    index_var: index

- name: Role dependencies.
  include_role:
    name: ansible-role-linux-nginx
  vars:
    ngx_port_http: '{{ minio_ngx_port_http }}'
    ngx_port_https: '{{ minio_ngx_port_https }}'
    ngx_compress: false
    ngx_block_agents: true
    ngx_block_string: true
    ngx_ssl_protocols: 'modern'
    ngx_site_path: '{{ minio_path }}/nginx/site'
    ngx_logs_path: '{{ minio_path }}/nginx/logs'
    ngx_allow_methods:
      - 'POST'
      - 'PUT'
      - 'GET'
      - 'HEAD'
      - 'DELETE'
    ngx_site: '{{ minio_ngx_site }}'
