---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add EPEL YUM repositories
  yum_repository:
    name: '{{ epel_repo_name }}'
    description: '{{ epel_repo_name }} YUM repo'
    file: '{{ epel_repo_name }}'
    baseurl: '{{ epel_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the dependents packages
  yum:
    name: '{{ minio_dependent_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
    update_cache: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5
