---
- name: Register exporter service with an http health check
  uri:
    url: '{{ consul_public_http_prot }}://{{ consul_public_clients_item }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'PUT'
    body: '{"tags":["prometheus","exporter"],"ID":"{{ inventory_hostname | upper }}_minio_exporter_t_{{ item | upper }}","name":"minio_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ minio_start_port | int + 1 + index }},"meta":{"metrics_path":"/minio/prometheus/metrics","instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}","tenant":"{{ item | upper }}"{% if tags is defined %},{{ tags | to_json | regex_replace("{") | regex_replace("}") }}{% endif %}},"checks":[{"http":"http://{{ ansible_default_ipv4.address }}:{{ minio_start_port | int + 1 + index }}/minio/prometheus/metrics","interval":"60s","tls_skip_verify":true,"method":"HEAD","timeout":"10s"}]}'
    body_format: 'json'
    status_code: '200'
    headers:
      X-Consul-Token: '{{ consul_public_exporter_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ consul_public_clients_item }}'
  loop: '{{ minio_tenants }}'
  loop_control:
    index_var: index
  when: consul_public_register | bool
  register: register_status
  until: register_status.status == 200
  retries: 3
  delay: 3
  no_log: true
  changed_when: false
  failed_when: false
