---
- name: Enable Minio service
  systemd:
    name: 'minio-T{{ item|int }}.service'
    enabled: yes
    state: restarted
    daemon_reload: yes
  async: 1
  poll: 0
  with_sequence: start=1 end={{ minio_tenants|int }}
  listen: Ensure minio service is enabled
